apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master-workload-controller
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: NotIn
                    values: [hub]

          - git:
              repoURL: https://github.com/segoja7/demo_cncf_latam_summit/
              revision: HEAD
              directories:
                - path: dev_consumer/*

  template:
    metadata:
      name: '{{.path.basename}}-{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/segoja7/demo_cncf_latam_summit/
        targetRevision: HEAD
        path: '{{.path.path}}'
        plugin:
          name: kcl-v1.0
      destination:
        name: '{{.name}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true