apiVersion: segoja7.example/v1alpha1
kind: XCLUSTER
metadata:
  name: spoke2
spec:
  id: spoke2
  region: us-east-1
  providerConfigName: segoja7
  tags:
    owner: "platform-team"
    environment: "development"
    project: "proyecto"
    managed-by: "crossplane"
  accountId: "476114125818"
  encryptCluster: false
  authenticationMode: "API_AND_CONFIG_MAP"
  logging:
    - "api" 
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
  endpointPublicAccess: true
  endpointPrivateAccess: true
  publicAccessCidrs: 
    - "0.0.0.0/0"
  networkId: "xnetwork-example"
  clusterVersion: "1.33"
  nodeGroup:
    amiType: "BOTTLEROCKET_ARM_64"
    capacityType: "ON_DEMAND"
    diskSize: 20
    instanceTypes: 
     - "t4g.large"
    minSize: 1
    maxSize: 3
    desiredSize: 1
    updateConfig:
      maxUnavailablePercentage: 25
      force: true
  addons:
   - name: eks-pod-identity-agent
     version: "v1.3.8-eksbuild.2"
     resolveConflicts: "OVERWRITE"
   - name: vpc-cni
    #  version: "latest"
     resolveConflicts: "OVERWRITE"
   - name: coredns
    #  version: "latest"
     resolveConflicts: "OVERWRITE"
   - name: kube-proxy
    #  version: "latest"
     resolveConflicts: "OVERWRITE"
  hostedZoneID: "Z084056021QR5BJUSPGN7"
  domainNames: 
   - "*.segoja7.com"
  certificateSecretName: "ssl-wildcard-idp"
  enableArgo: false
  clusterTopology:
    typeCluster: Spoke
    hubId: hub   